# Generated by Django 5.1.1 on 2025-03-15 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='doctor',
            new_name='d_email',
        ),
    ]
